author           = InnovAnon
depends          = default,futil,ia_util
description      = Unique names for players and entities
name             = ia_names
optional_depends =
title            = IA Names

